[package]
name = "webfishing_macos_installer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
steamlocate = "2.0.0"
sysinfo = "0.33.0"
async-std = "1.13.0"
sudo = "0.6.0"
asky = "0.1.1"