name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: webfishing-macos-installer
        path: /Users/runner/work/webfishing-macos-installer/webfishing-macos-installer/target/release/webfishing_macos_installer
